import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ScanResult } from "../services/scannerService";

export function generateSecurityReport(
  result: ScanResult,
  website: string
) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const scanDate = new Date().toLocaleString();

  // ---------------------------------------
// Report Metadata
// ---------------------------------------

const reportId =
  "CS-" +
  Date.now().toString().slice(-8);

const generatedBy = "CyberShield v1.0";

const classification = "CONFIDENTIAL";

  //---------------------------------------
  // Risk Calculation
  //---------------------------------------

  const risk =
    result.securityScore >= 90
      ? "LOW"
      : result.securityScore >= 70
      ? "MEDIUM"
      : "HIGH";

  //---------------------------------------
  // Statistics
  //---------------------------------------

  const totalHeaders = 6;

  const enabledHeaders = [
    result.hasHsts,
    result.hasCsp,
    result.hasXFrameOptions,
    result.hasXContentTypeOptions,
    result.hasReferrerPolicy,
    result.hasPermissionsPolicy,
  ].filter(Boolean).length;

  const totalPorts = result.openPorts.filter(
    (p) => p.isOpen
  ).length;

  const vulnerabilityCount =
    result.vulnerabilities.length;

  //---------------------------------------
  // Banner
  //---------------------------------------

  doc.setFillColor(15, 23, 42);

doc.rect(
  0,
  0,
  pageWidth,
  55,
  "F"
);

doc.setTextColor(255);

doc.setFontSize(30);

doc.text(
  "CyberShield",
  pageWidth / 2,
  22,
  {
    align: "center",
  }
);

doc.setFontSize(15);

doc.text(
  "Enterprise Website Security Assessment",
  pageWidth / 2,
  34,
  {
    align: "center",
  }
);

doc.setFontSize(11);

doc.text(
  classification,
  pageWidth / 2,
  45,
  {
    align: "center",
  }
);

  //---------------------------------------
  // Website Info
  //---------------------------------------

  doc.setTextColor(0);

  doc.setFontSize(18);

  doc.text(
  "Executive Summary",
  14,
  52
);

doc.setDrawColor(220);

doc.line(
  14,
  55,
  196,
  55
);

  doc.setFontSize(11);

doc.text(`Report ID : ${reportId}`, 14, 84);
doc.text(`Website : ${website}`, 14, 92);
doc.text(`Generated : ${scanDate}`, 14, 100);
doc.text(`Generated By : ${generatedBy}`, 14, 108);

  //---------------------------------------
// Summary Cards
//---------------------------------------

const cardY = 118;

const drawCard = (
  x: number,
  y: number,
  title: string,
  value: string,
  color: number[]
) => {
  doc.setFillColor(color[0], color[1], color[2]);

  doc.roundedRect(
    x,
    y,
    42,
    28,
    3,
    3,
    "F"
  );

  doc.setTextColor(255);

  doc.setFontSize(10);

  doc.text(
    title,
    x + 21,
    y + 9,
    {
      align: "center",
    }
  );

  doc.setFontSize(18);

  doc.text(
    value,
    x + 21,
    y + 20,
    {
      align: "center",
    }
  );
};

drawCard(
  14,
  cardY,
  "Score",
  `${result.securityScore}`,
  [37, 99, 235]
);

drawCard(
  60,
  cardY,
  "Grade",
  result.grade,
  [22, 163, 74]
);

drawCard(
  106,
  cardY,
  "Risk",
  risk,
  risk === "LOW"
    ? [22, 163, 74]
    : risk === "MEDIUM"
    ? [234, 179, 8]
    : [220, 38, 38]
);

drawCard(
  152,
  cardY,
  "SSL",
  result.isCertificateValid
    ? "VALID"
    : "INVALID",
  result.isCertificateValid
    ? [22, 163, 74]
    : [220, 38, 38]
);

//---------------------------------------
// Overall Security Rating
//---------------------------------------

const ratingY = 154;

doc.setFillColor(239, 246, 255);

doc.roundedRect(
  14,
  ratingY,
  182,
  28,
  3,
  3,
  "F"
);

doc.setTextColor(30, 41, 59);

doc.setFontSize(14);

doc.text(
  "Overall Security Rating",
  20,
  ratingY + 12
);

doc.setFontSize(20);

doc.setTextColor(
  result.securityScore >= 90
    ? 22
    : result.securityScore >= 70
    ? 202
    : 220,
  result.securityScore >= 90
    ? 163
    : result.securityScore >= 70
    ? 138
    : 38,
  result.securityScore >= 90
    ? 74
    : result.securityScore >= 70
    ? 4
    : 38
);

doc.text(
  result.grade,
  175,
  ratingY + 14,
  {
    align: "right",
  }
);

  //---------------------------------------
  // Statistics
  //---------------------------------------

  doc.setTextColor(0);

  doc.setFontSize(16);

  doc.text(
  "Scan Statistics",
  14,
  198
);

autoTable(doc, {
  startY: 204,

    head: [
      [
        "Metric",
        "Value",
      ],
    ],

    body: [
      [
        "Security Score",
        `${result.securityScore}/100`,
      ],

      [
        "Security Grade",
        result.grade,
      ],

      [
        "Risk Level",
        risk,
      ],

      [
        "SSL Certificate",
        result.isCertificateValid
          ? "Valid"
          : "Invalid",
      ],

      [
        "Headers Enabled",
        `${enabledHeaders}/${totalHeaders}`,
      ],

      [
        "Open Ports",
        totalPorts.toString(),
      ],

      [
        "Vulnerabilities",
        vulnerabilityCount.toString(),
      ],
    ],

    styles: {
      fontSize: 10,
    },

    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  const totalPages = doc.getNumberOfPages();

for (let i = 1; i <= totalPages; i++) {

  doc.setPage(i);

  doc.setTextColor(235);

  doc.setFontSize(48);

  doc.text(
    "CYBERSHIELD",
    105,
    160,
    {
      align: "center",
      angle: 45,
    }
  );
}

  //---------------------------------------
  // Footer Function
  //---------------------------------------

  const addFooter = () => {

  const pages =
    doc.getNumberOfPages();

  for (
    let i = 1;
    i <= pages;
    i++
  ) {

    doc.setPage(i);

    doc.setDrawColor(220);

    doc.line(
      14,
      pageHeight - 14,
      pageWidth - 14,
      pageHeight - 14
    );

    doc.setFontSize(9);

    doc.setTextColor(120);

    doc.text(
      `CyberShield Security Report`,
      14,
      pageHeight - 8
    );

    doc.text(
      reportId,
      pageWidth / 2,
      pageHeight - 8,
      {
        align: "center",
      }
    );

    doc.text(
      `Page ${i} of ${pages}`,
      pageWidth - 14,
      pageHeight - 8,
      {
        align: "right",
      }
    );
  }
};

  // Remaining report sections will be added
  // in Part 2 before calling addFooter()
  // ---------------------------------------
// SSL Certificate
// ---------------------------------------

doc.addPage();

doc.setFontSize(18);
doc.setTextColor(0);

doc.text("SSL Certificate Analysis", 14, 20);

autoTable(doc, {
  startY: 28,

  head: [["Property", "Value"]],

  body: [
    [
      "Certificate Status",
      result.isCertificateValid ? "Valid" : "Invalid",
    ],
    [
      "Issuer",
      result.certificateIssuer || "N/A",
    ],
    [
      "Subject",
      result.certificateSubject || "N/A",
    ],
    [
      "Expiry Date",
      result.certificateExpiryDate || "N/A",
    ],
    [
      "Days Remaining",
      result.daysUntilExpiry.toString(),
    ],
  ],

  headStyles: {
    fillColor: [37, 99, 235],
  },

  didParseCell(data) {
    if (
      data.section === "body" &&
      data.row.index === 0 &&
      data.column.index === 1
    ) {
      const value = String(data.cell.raw);

      if (value === "Valid") {
        data.cell.styles.textColor = [22, 163, 74];
      } else {
        data.cell.styles.textColor = [220, 38, 38];
      }

      data.cell.styles.fontStyle = "bold";
    }
  },
});

// ---------------------------------------
// Security Headers
// ---------------------------------------

doc.setFontSize(18);

doc.text(
  "Security Headers",
  14,
  (doc as any).lastAutoTable.finalY + 15
);

autoTable(doc, {
  startY: (doc as any).lastAutoTable.finalY + 22,

  head: [["Header", "Status"]],

  body: [
    ["HSTS", result.hasHsts],
    ["Content Security Policy", result.hasCsp],
    ["X-Frame-Options", result.hasXFrameOptions],
    [
      "X-Content-Type-Options",
      result.hasXContentTypeOptions,
    ],
    [
      "Referrer Policy",
      result.hasReferrerPolicy,
    ],
    [
      "Permissions Policy",
      result.hasPermissionsPolicy,
    ],
  ],

  headStyles: {
    fillColor: [37, 99, 235],
  },

  didParseCell(data) {
    if (
      data.section === "body" &&
      data.column.index === 1
    ) {
      const enabled =
        data.cell.raw === true;

      data.cell.text = [
        enabled
          ? "Enabled"
          : "Missing",
      ];

      data.cell.styles.textColor = enabled
        ? [22, 163, 74]
        : [220, 38, 38];

      data.cell.styles.fontStyle = "bold";
    }
  },
});

// ---------------------------------------
// Open Ports
// ---------------------------------------

doc.setFontSize(18);

doc.text(
  "Open Ports",
  14,
  (doc as any).lastAutoTable.finalY + 15
);

autoTable(doc, {
  startY: (doc as any).lastAutoTable.finalY + 22,

  head: [["Port", "Service", "Status"]],

  body:
    result.openPorts.length > 0
      ? result.openPorts.map((p) => [
          p.port,
          p.service,
          p.isOpen ? "Open" : "Closed",
        ])
      : [["-", "No Ports", "-"]],

  headStyles: {
    fillColor: [37, 99, 235],
  },

  didParseCell(data) {
    if (
      data.section === "body" &&
      data.column.index === 2
    ) {
      const value = String(data.cell.raw);

      if (value === "Open") {
        data.cell.styles.textColor = [220, 38, 38];
      } else {
        data.cell.styles.textColor = [22, 163, 74];
      }

      data.cell.styles.fontStyle = "bold";
    }
  },
});

doc.setDrawColor(220);
doc.line(
  14,
  (doc as any).lastAutoTable.finalY + 10,
  196,
  (doc as any).lastAutoTable.finalY + 10
);

// ---------------------------------------
// Vulnerabilities
// ---------------------------------------

doc.addPage();

doc.setFontSize(18);
doc.setTextColor(0);

doc.text("Detected Vulnerabilities", 14, 20);

autoTable(doc, {
  startY: 28,

  head: [[
    "Severity",
    "Vulnerability",
    "Description",
    "Recommendation",
  ]],

  body:
    result.vulnerabilities.length > 0
      ? result.vulnerabilities.map(v => [
          v.severity,
          v.name,
          v.description,
          v.recommendation,
        ])
      : [[
          "-",
          "No Vulnerabilities",
          "No vulnerabilities were detected.",
          "-"
        ]],

  styles: {
    fontSize: 9,
    cellPadding: 3,
    overflow: "linebreak",
    valign: "middle",
  },

  headStyles: {
    fillColor: [37, 99, 235],
    textColor: [255, 255, 255],
    fontStyle: "bold",
  },

  columnStyles: {
    0: { cellWidth: 25 },
    1: { cellWidth: 40 },
    2: { cellWidth: 60 },
    3: { cellWidth: 60 },
  },

  didParseCell(data) {

    if (
      data.section === "body" &&
      data.column.index === 0
    ) {

      const severity = String(data.cell.raw).toLowerCase();

      if (severity === "critical") {
        data.cell.styles.textColor = [127, 29, 29];
        data.cell.styles.fillColor = [254, 202, 202];
      }

      else if (severity === "high") {
        data.cell.styles.textColor = [220, 38, 38];
        data.cell.styles.fillColor = [254, 226, 226];
      }

      else if (severity === "medium") {
        data.cell.styles.textColor = [202, 138, 4];
        data.cell.styles.fillColor = [254, 249, 195];
      }

      else if (severity === "low") {
        data.cell.styles.textColor = [22, 163, 74];
        data.cell.styles.fillColor = [220, 252, 231];
      }

      data.cell.styles.fontStyle = "bold";
    }
  }
});

doc.setFontSize(18);

doc.text(
  "Security Recommendations",
  14,
  (doc as any).lastAutoTable.finalY + 18
);

const recommendations: string[] = [];

if (!result.hasHsts)
  recommendations.push("Enable Strict-Transport-Security (HSTS).");

if (!result.hasCsp)
  recommendations.push("Implement a Content-Security-Policy.");

if (!result.hasXFrameOptions)
  recommendations.push("Enable X-Frame-Options.");

if (!result.hasXContentTypeOptions)
  recommendations.push("Enable X-Content-Type-Options.");

if (!result.hasReferrerPolicy)
  recommendations.push("Configure Referrer Policy.");

if (!result.hasPermissionsPolicy)
  recommendations.push("Implement Permissions Policy.");

if (!result.isCertificateValid)
  recommendations.push("Renew SSL certificate.");

if (result.openPorts.some(p => p.isOpen))
  recommendations.push("Close unnecessary open ports.");

if (result.vulnerabilities.length > 0)
  recommendations.push("Resolve detected vulnerabilities.");

autoTable(doc, {

  startY: (doc as any).lastAutoTable.finalY + 24,

  head: [["#", "Recommendation"]],

  body:
    recommendations.length > 0
      ? recommendations.map((r, i) => [
          i + 1,
          r,
        ])
      : [[1, "No recommendations. Excellent security posture."]],

  headStyles: {
    fillColor: [22, 163, 74],
  },

  styles: {
    fontSize: 10,
  },
});

doc.setFontSize(18);

doc.text(
  "Executive Conclusion",
  14,
  (doc as any).lastAutoTable.finalY + 18
);

let conclusion = "";

if (result.securityScore >= 90) {

  conclusion =
    "The assessed website demonstrates a strong security posture. Security headers are properly configured, SSL is valid, and only minimal improvements are recommended.";

}
else if (result.securityScore >= 70) {

  conclusion =
    "The website has a generally acceptable security configuration but several improvements are recommended to reduce potential attack surfaces.";

}
else {

  conclusion =
    "The assessment identified significant security weaknesses that should be addressed as soon as possible. Missing headers, exposed services, or detected vulnerabilities increase the overall security risk.";

}

doc.setFontSize(11);

doc.text(
  conclusion,
  14,
  (doc as any).lastAutoTable.finalY + 28,
  {
    maxWidth: 180,
  }
);

doc.roundedRect(
  14,
  (doc as any).lastAutoTable.finalY + 45,
  182,
  35,
  3,
  3
);

doc.setFontSize(18);

doc.text(
  "Final Summary",
  14,
  250
);

doc.setFontSize(11);

doc.text(
  "This report summarizes the security posture of the assessed website based on SSL configuration, HTTP security headers, exposed network ports, and detected vulnerabilities. The findings should be reviewed and appropriate remediation actions should be taken where applicable.",
  14,
  260,
  {
    maxWidth: 180,
  }
);

  addFooter();

  doc.save(
    "CyberShield-Security-Report.pdf"
  );
}